<?php

return [
    [
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'dashboard',
        'active_pattern' => 'dashboard',
        'exclude_role' => 'School Admin',
    ],
    [
        'label' => 'Courses',
        'route' => 'courses.index',
        'icon' => 'school',
        'active_pattern' => 'courses.*|sessions.*',
        'requires_permission' => 'courses.view',
        'requires_school' => true,
        'exclude_role' => 'School Admin',
    ],
    [
        'label' => 'Media Library',
        'route' => 'media-library.index',
        'icon' => 'perm_media',
        'active_pattern' => 'media-library.*',
        'requires_permission' => 'media.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Users',
        'route' => 'users.index',
        'icon' => 'group',
        'active_pattern' => 'users.*',
        'requires_permission' => 'users.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Roles',
        'route' => 'roles.index',
        'icon' => 'shield',
        'active_pattern' => 'roles.*',
        'requires_permission' => 'roles.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Permissions',
        'route' => 'permissions.index',
        'icon' => 'key',
        'active_pattern' => 'permissions.*',
        'requires_permission' => 'permissions.view',
        'requires_school' => true,
    ],
    [
        'label' => 'My Schools',
        'route' => 'manage.schools.index',
        'icon' => 'apartment',
        'active_pattern' => 'manage.schools.index',
        'requires_role' => 'School Admin',
        'requires_no_school' => true,
    ],
    [
        'label' => 'Transactions',
        'route' => 'transactions.index',
        'icon' => 'receipt_long',
        'active_pattern' => 'transactions.index',
        'requires_role' => 'School Admin',
        'requires_no_school' => true,
    ],
];
