<?php

use App\Enums\RoleName;

return [
    [
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'dashboard',
        'active_pattern' => 'dashboard',
        'exclude_role' => RoleName::SchoolAdmin->value,
    ],
    [
        'label' => 'Courses',
        'route' => 'courses.index',
        'icon' => 'school',
        'active_pattern' => 'courses.*|sessions.*',
        'requires_permission' => 'courses.view',
        'requires_school' => true,
        'exclude_role' => RoleName::SchoolAdmin->value,
    ],
    [
        'label' => 'Students',
        'route' => 'students.index',
        'icon' => 'groups',
        'active_pattern' => 'students.*',
        'requires_permission' => 'students.view',
        'requires_role' => RoleName::SchoolAdmin->value,
        'requires_school' => true,
    ],
    [
        'label' => 'Teachers',
        'route' => 'teachers.index',
        'icon' => 'person',
        'active_pattern' => 'teachers.*',
        'requires_permission' => 'teachers.view',
        'requires_role' => RoleName::SchoolAdmin->value,
        'requires_school' => true,
    ],
    [
        'label' => 'Raport',
        'route' => 'raport.index',
        'icon' => 'summarize',
        'active_pattern' => 'raport.*',
        'requires_permission' => 'raport.view',
        'requires_school' => true,
        'exclude_role' => RoleName::Teacher->value,
    ],
    [
        'label' => 'Media Library',
        'route' => 'media-library.index',
        'icon' => 'perm_media',
        'active_pattern' => 'media-library.*',
        'requires_permission' => 'media.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Roles',
        'route' => 'roles.index',
        'icon' => 'shield',
        'active_pattern' => 'roles.*',
        'requires_permission' => 'roles.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Permissions',
        'route' => 'permissions.index',
        'icon' => 'key',
        'active_pattern' => 'permissions.*',
        'requires_permission' => 'permissions.view',
        'requires_school' => true,
    ],
    [
        'label' => 'My Schools',
        'route' => 'manage.schools.index',
        'icon' => 'apartment',
        'active_pattern' => 'manage.schools.index',
        'requires_role' => RoleName::SchoolAdmin->value,
        'requires_no_school' => true,
    ],
    [
        'label' => 'Transactions',
        'route' => 'transactions.index',
        'icon' => 'receipt_long',
        'active_pattern' => 'transactions.index',
        'requires_role' => RoleName::SchoolAdmin->value,
        'requires_no_school' => true,
    ],
];
