<?php

return [
    [
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'dashboard',
        'active_pattern' => 'dashboard',
        'exclude_role' => 'School Admin',
    ],
    [
        'label' => 'Courses',
        'route' => 'courses.index',
        'icon' => 'school',
        'active_pattern' => 'courses.*|lessons.*',
        'requires_permission' => 'courses.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Assignments',
        'route' => 'assignments.index',
        'icon' => 'assignment',
        'active_pattern' => 'assignments.*',
        'requires_permission' => 'assignments.view',
        'exclude_role' => 'Student',
        'requires_school' => true,
    ],
    [
        'label' => 'Grading Queue',
        'route' => 'grading-queue.index',
        'icon' => 'fact_check',
        'active_pattern' => 'grading-queue.*|submissions.override',
        'requires_permission' => 'submissions.grade',
        'requires_school' => true,
    ],
    [
        'label' => 'My Submissions',
        'route' => 'submissions.index',
        'icon' => 'assignment_turned_in',
        'active_pattern' => 'submissions.*',
        'requires_permission' => 'submissions.view',
        'exclude_role' => 'Instructor',
        'requires_school' => true,
    ],
    [
        'label' => 'Users',
        'route' => 'users.index',
        'icon' => 'group',
        'active_pattern' => 'users.*',
        'requires_permission' => 'users.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Roles',
        'route' => 'roles.index',
        'icon' => 'shield',
        'active_pattern' => 'roles.*',
        'requires_permission' => 'roles.view',
        'requires_school' => true,
    ],
    [
        'label' => 'Permissions',
        'route' => 'permissions.index',
        'icon' => 'key',
        'active_pattern' => 'permissions.*',
        'requires_permission' => 'permissions.view',
        'requires_school' => true,
    ],
    [
        'label' => 'My Schools',
        'route' => 'manage.schools.index',
        'icon' => 'apartment',
        'active_pattern' => 'manage.schools.index',
        'requires_role' => 'School Admin',
    ],
];
