<?php

namespace App\Livewire\Concerns;

use App\Enums\MaterialType;
use App\Services\MediaLibraryService;
use App\Services\R2StorageService;
use Illuminate\Support\Str;

trait WithDevMaterialAttachments
{
    /**
     * Reuses up to two of the school's existing media library items so dev
     * tooling exercises the attachment flow; generates a throwaway PDF item
     * when the library is empty so the result is never left without one.
     *
     * @return array<int, string>
     */
    private function devMaterialIds(string $schoolId, MediaLibraryService $mediaLibraryService, R2StorageService $r2StorageService): array
    {
        $existingIds = $mediaLibraryService->list($schoolId)->limit(2)->pluck('id')->all();
        if ($existingIds !== []) {
            return $existingIds;
        }

        $content = "%PDF-1.4\n"
            .'1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj'."\n"
            .'2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj'."\n"
            .'3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]/Resources<<>>/Contents 4 0 R>>endobj'."\n"
            .'4 0 obj<</Length 44>>stream'."\n"
            .'BT /F1 18 Tf 20 100 Td (Assessment Attachment) Tj ET'
            ."\nendstream endobj\n"
            .'trailer<</Size 5/Root 1 0 R>>'."\n"
            .'%%EOF';

        $key = $r2StorageService->schoolPrefix().'media/dev-generated/assessment-'.Str::uuid().'.pdf';

        $item = $mediaLibraryService->createFromRawContent($schoolId, auth()->id(), $key, $content, 'application/pdf', [
            'type' => MaterialType::PDF,
            'title' => 'Dev Tools Attachment.pdf',
            'description' => 'Generated by dev tooling.',
        ]);

        return [$item->id];
    }
}
